import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'screens/auth_screen.dart';
import 'screens/home_screen.dart';
import 'screens/map_screen.dart';
import 'screens/passport_screen.dart';
import 'screens/events_screen.dart';
import 'screens/favorites_screen.dart';
import 'screens/reviews_screen.dart';
import 'screens/submit_review_screen.dart';

import 'firebase_options.dart'; // <-- generated by flutterfire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const IntanAgKapeApp());
}

class IntanAgKapeApp extends StatelessWidget {
  const IntanAgKapeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Intan Ag-Kape',
      theme: ThemeData(
        primarySwatch: Colors.brown,
        scaffoldBackgroundColor: const Color(0xFFFDF6F0),
        fontFamily: 'Roboto',
        useMaterial3: true,
      ),
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      onGenerateRoute: (settings) {
        switch (settings.name) {
          case '/':
            final user = FirebaseAuth.instance.currentUser;
            return MaterialPageRoute(
              builder: (_) => user == null ? const AuthScreen() : const HomeScreen(),
            );
          case '/map':
            final weather = settings.arguments as String? ?? 'Clear';
            return MaterialPageRoute(
              builder: (_) => MapScreen(weather: weather),
            );
          case '/passport':
            return MaterialPageRoute(builder: (_) => const PassportScreen());
          case '/events':
            return MaterialPageRoute(builder: (_) => const EventsScreen());
          case '/favorites':
            return MaterialPageRoute(builder: (_) => const FavoritesScreen());
          case '/reviews':
            return MaterialPageRoute(builder: (_) => const ReviewsScreen());
          case '/submit-review':
            return MaterialPageRoute(builder: (_) => const SubmitReviewScreen());
          default:
            return MaterialPageRoute(
              builder: (_) => const Scaffold(
                body: Center(child: Text("Route not found")),
              ),
            );
        }
      },
    );
  }
}
